### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/Sightstone#3]
Required to be done as soon as possible
- [ ] Finish Sightstone.Core
  - [ ] Finish all XMPP functions
  - [ ] Finish all RTMP functions
  - [ ] Finish all Account logic
- [ ] Finish the UI
- [ ] Finish the code behind the UI
